/*
 * Pixel Dungeon
 * Copyright (C) 2012-2015 Oleg Dolya
 *
 * Shattered Pixel Dungeon
 * Copyright (C) 2014-2026 Evan Debenham
 *
 * Warped Pixel Dungeon
 * Copyright (C) 2026 Gabriel Duarte Guerra (gabriwar)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */

package xyz.gabriwar.warpedpixeldungeon.windows;

import xyz.gabriwar.warpedpixeldungeon.items.Item;
import org.junit.Test;

import java.io.IOException;
import java.lang.reflect.Modifier;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.TreeSet;
import java.util.stream.Stream;

import static org.junit.Assert.fail;

/**
 * The debug menu's ALL ITEMS list (DebugItems) must hold every public, constructible
 * Item class. It is a generated file (Android cannot scan its own classes at run time),
 * so this test keeps it honest: it scans the compiled classes, and when the list is
 * stale it REWRITES DebugItems.java with the full set and fails once, so the next
 * build carries every item. Same filter as tools/tests/GenerateDebugItems.java.
 */
public class DebugItemsCompleteTest {

	private static final String SOURCE = "src/main/java/xyz/gabriwar/warpedpixeldungeon/windows/DebugItems.java";

	@Test
	public void debugMenuListsEveryItem() throws Exception {
		Path root = Paths.get( Item.class.getProtectionDomain().getCodeSource().getLocation().toURI() );
		TreeSet<String> all = new TreeSet<>();
		try (Stream<Path> paths = Files.walk( root )){
			for (Path path : (Iterable<Path>) paths.filter( p -> p.toString().endsWith( ".class" ) )::iterator){
				String name = root.relativize( path ).toString()
						.replace( '/', '.' ).replace( '\\', '.' ).replace( ".class", "" );
				Class<?> cls;
				try {
					cls = Class.forName( name, false, getClass().getClassLoader() );
				} catch (Throwable t){
					continue;
				}
				if (cls == Item.class || !Item.class.isAssignableFrom( cls ) || Modifier.isAbstract( cls.getModifiers() )
						|| !Modifier.isPublic( cls.getModifiers() ) || cls.isAnonymousClass() || cls.isLocalClass()
						|| cls.getCanonicalName() == null) continue;
				try { cls.getConstructor(); } catch (NoSuchMethodException e){ continue; }
				all.add( cls.getCanonicalName() );
			}
		}

		TreeSet<String> listed = new TreeSet<>();
		for (Class<?> c : DebugItems.ALL) listed.add( c.getCanonicalName() );
		if (listed.equals( all )) return;

		TreeSet<String> missing = new TreeSet<>( all );
		missing.removeAll( listed );
		TreeSet<String> gone = new TreeSet<>( listed );
		gone.removeAll( all );
		rewrite( all );
		fail( "DebugItems.java was stale and has been regenerated (" + all.size() + " items); rebuild to pick it up."
				+ (missing.isEmpty() ? "" : "\nwas missing: " + missing)
				+ (gone.isEmpty() ? "" : "\nno longer items: " + gone) );
	}

	private static void rewrite( TreeSet<String> names ) throws IOException {
		StringBuilder out = new StringBuilder( "package xyz.gabriwar.warpedpixeldungeon.windows;\n\n"
				+ "// Generated by tools/tests/GenerateDebugItems.java from all public, constructible Item classes.\n"
				+ "// Independent of loot probabilities and journal discovery.\n"
				+ "// Kept complete by DebugItemsCompleteTest, which rewrites this file when an item is missing.\n"
				+ "final class DebugItems {\n    static final Class<?>[] ALL = {\n" );
		for (String name : names) out.append( "        " ).append( name ).append( ".class,\n" );
		out.append( "    };\n    private DebugItems() {}\n}\n" );
		Files.write( Paths.get( SOURCE ), out.toString().getBytes( "UTF-8" ) );
	}
}
