/*
 * Pixel Dungeon
 * Copyright (C) 2012-2015 Oleg Dolya
 *
 * Shattered Pixel Dungeon
 * Copyright (C) 2014-2026 Evan Debenham
 *
 * Warped Pixel Dungeon
 * Copyright (C) 2026 Gabriel Duarte Guerra (gabriwar)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */

package xyz.gabriwar.warpedpixeldungeon.tiles;

import xyz.gabriwar.warpedpixeldungeon.Dungeon;
import xyz.gabriwar.warpedpixeldungeon.levels.Terrain;

/**
 * Where ice meets open water, the ice frays out over the water in loose pixels instead
 * of ending in a square edge: a layer drawn on every WATER or DEEP_WATER cell that
 * touches FROZEN_WATER, on every level, from environment/ice_fringe.png
 * (tools/dress_sheet.py): eight versions of the set, version v holding on row 2v the
 * side overlays (cell = side mask, 1=N 2=E 4=S 8=W) and on row 2v+1 the corners for
 * water that meets ice only at a diagonal (cell = corner mask, 1=NE 2=SE 4=SW 8=NW).
 *
 * Frozen falls use a region-specific atlas generated by IceFallTexture from the
 * bottom edge of the stitched pool tile above. Running neighbours retain the ice
 * creep overlays on row 19.
 *
 * Ice appears anywhere (frost freezes a pool mid-fight, cold levels, the overworld's
 * lakes), and GameScene.updateMap keeps the layer current as cells freeze and thaw.
 */
public class IceFringeTilemap extends DungeonTilemap {

	public IceFringeTilemap(){
		super( IceFallTexture.forLevel() );
		map( Dungeon.level.map, Dungeon.level.width() );
	}

	@Override
	protected int getTileVisual( int pos, int tile, boolean flat ){
		//ice at the lip of a chasm: its waterfall froze too. The icefall frays at a side
		//where the fall next to it still runs (bit 1 left, bit 2 right)
		if (tile == Terrain.CHASM){
			int fallVersion0 = (int)(((pos * 0x9E3779B1L) >>> 16) % ICEFALL_VARIANTS);
			//a running fall beside a frozen one: the ice creeps in from that side
			if (terrainAt( pos, 0, -1, Terrain.WATER ) || terrainAt( pos, 0, -1, Terrain.DEEP_WATER )){
				int frozenSides = 0;
				if (frozenFall( pos, -1 )) frozenSides |= 1;
				if (frozenFall( pos, 1 ))  frozenSides |= 2;
				return frozenSides == 0 ? -1 : ICECREEP_ROW + 4 * fallVersion0 + frozenSides;
			}
			if (!terrainAt( pos, 0, -1, Terrain.FROZEN_WATER )) return -1;
			int pool = pos - mapWidth;
			int mask = 0;
			if (!(Dungeon.level instanceof xyz.gabriwar.warpedpixeldungeon.levels.overworld.OverworldLevel)) {
				mask = DungeonTileSheet.stitchFrozenWaterTile(
						terrainAt(pool, 0, -1), terrainAt(pool, 1, 0),
						Terrain.CHASM, terrainAt(pool, -1, 0)) - DungeonTileSheet.FROZEN_WATER;
			}
			int runningSides = (runningFall(pos, -1) ? 1 : 0) | (runningFall(pos, 1) ? 2 : 0);
			return IceFallTexture.FIRST_TILE + 4 * mask + runningSides;
		}
		if (tile != Terrain.WATER && tile != Terrain.DEEP_WATER) return -1;
		int sides = 0;
		if (iceAt( pos, 0, -1 )) sides |= 1;
		if (iceAt( pos, 1, 0 ))  sides |= 2;
		if (iceAt( pos, 0, 1 ))  sides |= 4;
		if (iceAt( pos, -1, 0 )) sides |= 8;
		//one of the sheet's versions per cell, picked by position, so no two
		//neighbours repeat the same pixels
		int version = 32 * (int)(((pos * 0x9E3779B1L) >>> 16) % VARIANTS);
		if (sides != 0) return version + sides;
		int corners = 0;
		if (iceAt( pos, 1, -1 ))  corners |= 1;
		if (iceAt( pos, 1, 1 ))   corners |= 2;
		if (iceAt( pos, -1, 1 ))  corners |= 4;
		if (iceAt( pos, -1, -1 )) corners |= 8;
		return corners != 0 ? version + 16 + corners : -1;
	}

	//versions of every fringe tile on the sheet (tools/dress_sheet.py ICE_VARIANTS)
	private static final int VARIANTS = 8;

	private boolean iceAt( int pos, int dx, int dy ){
		return terrainAt( pos, dx, dy, Terrain.FROZEN_WATER );
	}

	private boolean terrainAt( int pos, int dx, int dy, int terrain ){
		return terrainAt(pos, dx, dy) == terrain;
	}

	private int terrainAt(int pos, int dx, int dy) {
		int x = pos % mapWidth + dx, y = pos / mapWidth + dy;
		if (x < 0 || y < 0 || x >= mapWidth || y >= map.length / mapWidth) return -1;
		return map[x + y * mapWidth];
	}

	//the chasm cell beside this one carries a waterfall that still runs
	private boolean runningFall( int pos, int dx ){
		return terrainAt( pos, dx, 0, Terrain.CHASM )
				&& (terrainAt( pos, dx, -1, Terrain.WATER ) || terrainAt( pos, dx, -1, Terrain.DEEP_WATER ));
	}

	//the chasm cell beside this one carries a frozen fall
	private boolean frozenFall( int pos, int dx ){
		return terrainAt( pos, dx, 0, Terrain.CHASM ) && terrainAt( pos, dx, -1, Terrain.FROZEN_WATER );
	}

	//the row after the icefalls: running falls taking ice in from a frozen neighbour
	private static final int ICECREEP_ROW = 32 * 8 + 48;

	//variants of the running-fall ice creep
	private static final int ICEFALL_VARIANTS = 4;

	@Override
	public synchronized void updateMapCell(int cell) {
		super.updateMapCell(cell);
		//The pool's north bank is two rows above its fall.
		if (cell + mapWidth < map.length) super.updateMapCell(cell + mapWidth);
	}

	@Override
	protected boolean needsRender( int pos ){
		return data[pos] >= 0;
	}
}
